import os
from datetime import timedelta


SECRET_KEY = os.getenv("SECRET_KEY")

SQLALCHEMY_DATABASE_URI = os.getenv("SQLALCHEMY_DATABASE_URI")

SQLALCHEMY_TRACK_MODIFICATIONS = os.getenv("SQLALCHEMY_TRACK_MODIFICATIONS")

JWT_ACCESS_TOKEN_EXPIRES = timedelta(days=7)

UPLOAD_FOLDER = os.getenv("UPLOAD_FOLDER")

MAIL_SERVER = os.getenv("MAIL_SERVER")

MAIL_PORT = os.getenv("MAIL_PORT")

MAIL_USERNAME = os.getenv("MAIL_USERNAME")

MAIL_PASSWORD = os.getenv("MAIL_PASSWORD")

MAIL_USE_SSL = os.getenv("MAIL_USE_TLS")

MAIL_USE_TLS = os.getenv("MAIL_USE_TLS")
