import os
from datetime import timedelta


SECRET_KEY = os.getenv('SECRET_KEY')

SQLALCHEMY_DATABASE_URI = os.getenv('SQLALCHEMY_DATABASE_URI')

SQLALCHEMY_TRACK_MODIFICATIONS = os.getenv('SQLALCHEMY_TRACK_MODIFICATIONS')

JWT_ACCESS_TOKEN_EXPIRES = timedelta(minutes=30)

UPLOAD_FOLDER = os.getenv('UPLOAD_FOLDER')